inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
  RunRailsCops: true

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

StringLiterals:
  EnforcedStyle: single_quotes

Rubocop/Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
